apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
