apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
stringData:
  MONGO_URI: "replace"
  REDIS_URL: "replace"
  JWT_ACCESS_SECRET: "replace"
  JWT_REFRESH_SECRET: "replace"
  GOOGLE_CLIENT_ID: "replace"
  GOOGLE_CLIENT_SECRET: "replace"
  GOOGLE_CALLBACK_URL: "replace"
  CLIENT_URL: "replace"
  HTTP_ELB: "true"
